### PR TITLE
Remove unused packages

### PR DESCRIPTION
**Pull request by tschaffter**
Benefits:
- Reduce the size of the docker image
- Build the docker image faster
- Reduce the number of PR that dependabot creates to updated packages

### CODE REVIEW

**Comment by tschaffter** [comment]
The error is due to the fact that the way we check that Python packages are listed in alphanumerical order does not ignore lines that start with "#" (comments).

**Comment by gkowalski** [comment]
I believe that Werkzeug is in use under the covers even though we don't call it directly.

**Comment by tschaffter** [comment]
@gkowalski That's right, Werkzeug is used indirectly. We don't need to include  it in *requirements.txt* (tested).

**Comment by tschaffter** [comment]
`connection` is the packages that includes Flask and many others.

```
# pip install connexion==2.7.0
Collecting connexion==2.7.0
  Downloading connexion-2.7.0-py2.py3-none-any.whl (77 kB)
     |████████████████████████████████| 77 kB 15.9 MB/s
Collecting PyYAML>=5.1
  Downloading PyYAML-5.3.1.tar.gz (269 kB)
     |████████████████████████████████| 269 kB 22.0 MB/s
Collecting jsonschema>=2.5.1
  Downloading jsonschema-3.2.0-py2.py3-none-any.whl (56 kB)
     |████████████████████████████████| 56 kB 44.0 MB/s
Collecting clickclick>=1.2
  Downloading clickclick-1.2.2-py2.py3-none-any.whl (9.8 kB)
Collecting flask>=1.0.4
  Downloading Flask-1.1.2-py2.py3-none-any.whl (94 kB)
     |████████████████████████████████| 94 kB 16.1 MB/s
Collecting inflection>=0.3.1
  Downloading inflection-0.5.1-py2.py3-none-any.whl (9.5 kB)
Collecting requests>=2.9.1
  Downloading requests-2.24.0-py2.py3-none-any.whl (61 kB)
     |████████████████████████████████| 61 kB 13.8 MB/s
Collecting openapi-spec-validator>=0.2.4
  Downloading openapi_spec_validator-0.2.9-py3-none-any.whl (25 kB)
Collecting six>=1.11.0
  Downloading six-1.15.0-py2.py3-none-any.whl (10 kB)
Requirement already satisfied: setuptools in /usr/local/lib/python3.8/site-packages (from jsonschema>=2.5.1->connexion==2.7.0) (50.3.0)
Collecting pyrsistent>=0.14.0
  Downloading pyrsistent-0.17.3.tar.gz (106 kB)
     |████████████████████████████████| 106 kB 26.7 MB/s
Collecting attrs>=17.4.0
  Downloading attrs-20.2.0-py2.py3-none-any.whl (48 kB)
     |████████████████████████████████| 48 kB 26.4 MB/s
Collecting click>=4.0
  Downloading click-7.1.2-py2.py3-none-any.whl (82 kB)
     |████████████████████████████████| 82 kB 20.2 MB/s
Collecting itsdangerous>=0.24
  Downloading itsdangerous-1.1.0-py2.py3-none-any.whl (16 kB)
Collecting Werkzeug>=0.15
  Downloading Werkzeug-1.0.1-py2.py3-none-any.whl (298 kB)
     |████████████████████████████████| 298 kB 34.1 MB/s
Collecting Jinja2>=2.10.1
  Downloading Jinja2-2.11.2-py2.py3-none-any.whl (125 kB)
     |████████████████████████████████| 125 kB 32.9 MB/s
Collecting certifi>=2017.4.17
  Downloading certifi-2020.6.20-py2.py3-none-any.whl (156 kB)
     |████████████████████████████████| 156 kB 33.5 MB/s
Collecting chardet<4,>=3.0.2
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133 kB)
     |████████████████████████████████| 133 kB 33.0 MB/s
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
  Downloading urllib3-1.25.10-py2.py3-none-any.whl (127 kB)
     |████████████████████████████████| 127 kB 35.9 MB/s
Collecting idna<3,>=2.5
  Downloading idna-2.10-py2.py3-none-any.whl (58 kB)
     |████████████████████████████████| 58 kB 76.9 MB/s
Collecting MarkupSafe>=0.23
  Downloading MarkupSafe-1.1.1-cp38-cp38-manylinux1_x86_64.whl (32 kB)
Building wheels for collected packages: PyYAML, pyrsistent
  Building wheel for PyYAML (setup.py) ... done
  Created wheel for PyYAML: filename=PyYAML-5.3.1-cp38-cp38-linux_x86_64.whl size=44619 sha256=09b8b10ac64aab77b97de8162d5d19c5aed13581fd3a761ceb4154a6d654faea
  Stored in directory: /tmp/pip-ephem-wheel-cache-8fbzpq5_/wheels/13/90/db/290ab3a34f2ef0b5a0f89235dc2d40fea83e77de84ed2dc05c
  Building wheel for pyrsistent (setup.py) ... done
  Created wheel for pyrsistent: filename=pyrsistent-0.17.3-cp38-cp38-linux_x86_64.whl size=55874 sha256=9b28ebd393e50a79d4bc7e21fb3ad1e730558371f851e5cc62fe758424c544a3
  Stored in directory: /tmp/pip-ephem-wheel-cache-8fbzpq5_/wheels/3d/22/08/7042eb6309c650c7b53615d5df5cc61f1ea9680e7edd3a08d2
Successfully built PyYAML pyrsistent
Installing collected packages: PyYAML, six, pyrsistent, attrs, jsonschema, click, clickclick, itsdangerous, Werkzeug, MarkupSafe, Jinja2, flask, inflection, certifi, chardet, urllib3, idna, requests, openapi-spec-validator, connexion
Successfully installed Jinja2-2.11.2 MarkupSafe-1.1.1 PyYAML-5.3.1 Werkzeug-1.0.1 attrs-20.2.0 certifi-2020.6.20 chardet-3.0.4 click-7.1.2 clickclick-1.2.2 connexion-2.7.0 flask-1.1.2 idna-2.10 inflection-0.5.1 itsdangerous-1.1.0 jsonschema-3.2.0 openapi-spec-validator-0.2.9 pyrsistent-0.17.3 requests-2.24.0 six-1.15.0 urllib3-1.25.10
root@18d3de3ad770:/opt/app# pip install psycopg2-binary==2.8.6
Collecting psycopg2-binary==2.8.6
  Downloading psycopg2_binary-2.8.6-cp38-cp38-manylinux1_x86_64.whl (3.0 MB)
     |████████████████████████████████| 3.0 MB 10.0 MB/s
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.8.6
root@18d3de3ad770:/opt/app# pip install requests==2.24.0
Requirement already satisfied: requests==2.24.0 in /usr/local/lib/python3.8/site-packages (2.24.0)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.8/site-packages (from requests==2.24.0) (1.25.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.8/site-packages (from requests==2.24.0) (2020.6.20)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.8/site-packages (from requests==2.24.0) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.8/site-packages (from requests==2.24.0) (3.0.4)
root@18d3de3ad770:/opt/app# pip install swagger-ui-bundle==0.0.8
Collecting swagger-ui-bundle==0.0.8
  Downloading swagger_ui_bundle-0.0.8-py3-none-any.whl (3.8 MB)
     |████████████████████████████████| 3.8 MB 8.6 MB/s
Requirement already satisfied: Jinja2>=2.0 in /usr/local/lib/python3.8/site-packages (from swagger-ui-bundle==0.0.8) (2.11.2)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.8/site-packages (from Jinja2>=2.0->swagger-ui-bundle==0.0.8) (1.1.1)
Installing collected packages: swagger-ui-bundle
Successfully installed swagger-ui-bundle-0.0.8
root@18d3de3ad770:/opt/app#
```

**Comment by tschaffter** [comment]
@gkowalski The package `connextion` provides most of the packages previously listed in `requirements.txt`.

> "Connexion - API first applications with OpenAPI/Swagger and Flask"
https://pypi.org/project/connexion/

**Pull request merged**
